### ISSUE TITLE
Run distributed : ERROR: ORTE_ERROR_LOG: Data unpack would read past end of buffer

### ISSUE THREAD

**Issue by hmilxin** [uber/horovod#133]
I had a error with multi-nodes/GPUs ,  ,,,  single node is well.
ORTE_ERROR_LOG: Data unpack would read past end of buffer in file base/plm_base_launch_support.c at line 1230
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:
* not finding the required libraries and/or binaries on one or more nodes. Please check your PATH and LD_LIBRARY_PATH settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------

I checked PATH and LD_LIBRARY_PATH is ok， and ssh  is ok。 
I don't know Why ? could you help me, tks.

**Comment by alsrgv** [comment]
@hmilxin, can you check this issue and see if it's applicable to you - https://github.com/open-mpi/ompi/issues/4437?

**Comment by hmilxin** [comment]
@alsrgv thank you, I checked that issue, and I used ompi_info, Found one note(1) Configure command line '--with-cuda=/usr/local/cuda'  , another note(2) Configure command line '--with-cuda' , But i run on note(2) is well,  So I re-installed with same configure, now it's ok. 

thanks again

But i down know why?

**Comment by jackdmarquez** [comment]
> > @alsrgv thank you, I checked that issue, and I used ompi_info, Found one note(1) Configure command line '--with-cuda=/usr/local/cuda' , another note(2) Configure command line '--with-cuda' , But i run on note(2) is well, So I re-installed with same configure, now it's ok.
> > thanks again
> > But i down know why?
> 
> how do you fix it? I am stuck here!

Could you solve it? I have the same problem but still not working

**Comment by alsrgv** [comment]
@shellhue, @jackdmarquez, can you make sure you have the same version of Open MPI >= 4.0.0 installed on all the machines?  You can install it using [this approach](https://github.com/horovod/horovod/blob/master/Dockerfile#L40).

**Comment by yellowcat8774** [comment]
@alsrgv I am running with openmpi 4.0.0 and running into this same issue. Already attempted installing with --with-cuda='/usr/local/cuda' flag and still seeing the same issue. I am not using Docker.
Any help is appreciated.

**Comment by 1367043971** [comment]
I have a question the same with you !
[viewer-System-Product-Name:07161] [[41977,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file base/plm_base_launch_support.c at line 1200
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
how do i fix it！thanks！
