### ISSUE TITLE
horovod with my custom data loader 

### ISSUE THREAD

**Issue by ankurhanda** [uber/horovod#160]
Hi @alsrgv I am using a custom implementation of u-net and the code is available here: https://github.com/ankurhanda/tf-unet 

Places where I use horovod are 
- https://github.com/ankurhanda/tf-unet/blob/master/UNet.py#L51-L57
- https://github.com/ankurhanda/tf-unet/blob/master/train_u-net.py#L107-L108

I was assuming that I'd have to increase the batch size as batch_size_per_gpu * number_of_gpus. However, the code returns 

2018-02-02 16:13:08.135262: E tensorflow/core/common_runtime/direct_session.cc:170] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 16936927232

I went back to changing the batch size to batch size per gpu which is 20 but I still get the same error. I've trained this network and it works fine on 1 GPU with a batch size of 20 for 320x240 image.  It is very likely that I'm missing something in the horovod set up. Could you please recommend - it all looks fine to me but clearly there's something not quite right! 

best

**Comment by ankurhanda** [comment]
I also think MNIST example isn't very convincing because the size of images is very small and you'd never catch ways where things can go wrong. Once this works out I'm happy to push that in to the main repo of horovod.

**Comment by alsrgv** [comment]
Can you un-comment this line https://github.com/ankurhanda/tf-unet/blob/master/train_u-net.py#L98?  Right now every TensorFlow process will place the model on first GPU.

Also, I didn't see `hvd.broadcast_global_variables()` or `hvd.BroadcastGlobalVariablesHook()` anywhere.  You should add it so that all your workers start from the same weights.

All these steps can be found in https://github.com/uber/horovod#usage.

There is one "convincing" example of training ResNet-50 on ImageNet - https://github.com/uber/horovod/blob/master/examples/keras_imagenet_resnet50.py.  It does use Keras though.

**Comment by ankurhanda** [comment]
I see -- sorry I should have read the documentation properly.

**Comment by alsrgv** [comment]
No worries!  Thanks for sharing the code by the way.  Makes it much easier to help :-)

**Comment by ankurhanda** [comment]
messaging to let you know that things are running good! If you wish to add this example in your codebase let me know https://github.com/ankurhanda/tf-unet/blob/master/train_u-net_horovod.py it is per-pixel image segmentation network. The network is nicely decoupled from the main code in a class and is fairly straight forward to understand.

**Comment by alsrgv** [comment]
I'll close this issue as it appears to be resolved.

**Comment by denfromufa** [comment]
Here is benchmark implementation of U-NET with Horovod, tested up to 8 GPUs:

https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/Segmentation/UNet_Industrial/model/unet.py
