### ISSUE TITLE
Importing module using external MPI library used 

### ISSUE THREAD

**Issue by lkmokadam** [uber/horovod#217]
Observation 1:  External library makes sure MPI is not re-initialized.
error:
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort

Observation 2:  External library do not follow above recommendation  
error:
Open MPI has detected that this process has attempted to initialize
MPI (via MPI_INIT or MPI_INIT_THREAD) more than once.  This is
erroneous.

Code to reproduce errors has provided in the attached zip file.

[bug_repro_code.zip](https://github.com/uber/horovod/files/1821143/bug_repro_code.zip)

**Comment by alsrgv** [comment]
@lkmokadam, would importing the library after you call `hvd.init()` work for you?  I.e. put `import horovod.tensorflow as hvd` and `hvd.init()` at the top of your python file.

As an enhancement, we could add check if MPI was initialized and then not-reinitialize it.  Additionally, if MPI was initialized without thread support we would print a WARNING because we would likely crash right after trying to retrieve rank or doing other operation.

**Comment by alsrgv** [comment]
This was implemented by #394.
