### ISSUE TITLE
Benchmark's scalability (weak/strong)

### ISSUE THREAD

**Issue by TimZaman** [uber/horovod#40]
I take it the benchmarks in the README are based on weak scaling? (i.e. batch size per process stays the same regardless of number of processes?). If it is weak scaling, you'd be solving a different problem than if you would divide the back size by the number of processes (strong scaling), also giving you worse results.

**Comment by alsrgv** [comment]
We've found that it's very hard to make strong scaling work well, and haven't heard of anybody reporting successful results.  This is mostly because at large batch sizes (e.g. =1) modern GPUs have a lot of overhead.

On the contrary, companies are pursuing modifications to SGD, such as [custom learning rate schedules](https://research.fb.com/wp-content/uploads/2017/06/imagenet1kin1h5.pdf) to make large-batch SGD work.
