### ISSUE TITLE
question: why nccl allgather is not supported?

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#430]
In horovod implementation, only MPI allgather is supported. Why isn't nccl allgather supported? any specific reasons? Thanks.

**Comment by vsuthichai** [comment]
I had been wondering the same thing.  I'm attempting to benchmark distributed training on a transformer model that is a part of OpenSeq2Seq.  The embedding gradients appear to be IndexedSlices.  The allreduce for IndexedSlice is implemented as 2 allgathers, which I've traced on the Horovod timeline to MPI allgather.  The MPI allgather lasts about 2-3 seconds and is a significant bottleneck for the embedding updates.  Wondering how this can be addressed.

**Comment by anpark** [comment]
Same question and i tested ncclallgather

P40 two nodes, 16 GPUS:  700000 * 128 gradients allgather cost 350ms, while mpi_allgather cost 450ms

but still not ideal for the scale, if 32GPUs, 64GPUs, allgather will more slow.

any one has idea for large scale IndexedSlice sum or average? I'll have to try gradient compress

**Comment by vsuthichai** [comment]
@anpark I have the same issue actually open for OpenSeq2Seq. 
 You can find more details about my situation there. 
 https://github.com/NVIDIA/OpenSeq2Seq/issues/204

**Comment by alsrgv** [comment]
@vsuthichai, it seems that your issue manifests due to the nature of AWS 10Gbit flow limits.  MPI hits 10Gbit limit since it opens only one TCP connection, but NCCL can open multiple connections and reach 25Gbit by using `NCCL_MIN_NRINGS=4`. I've provided more feedback [here](https://github.com/NVIDIA/OpenSeq2Seq/issues/204#issuecomment-411852769).

In general, here are the tradeoffs available:
1. MPI_AllgatherV on CPU - requires memory copy to CPU
2. NCCL_Allgather on GPU - requires memory copy on GPU for padding
3. MPI_AllgatherV on GPU - may deadlock with NCCL, not recommended

I think adding support for (2) would be a great new feature.

**Comment by Richie-yan** [comment]
HI， @alsrgv 
Recently, I'm using horovod to train a visual model. The model will execute allgather once at each step. Now I use MPI_Allgather on CPU. I implemented a simple NCCL_Allgather on GPU in the source code, and the performance has been greatly improved. What is your opinion on this patch and whether the community accepts the patch？

**Comment by tgaddair** [comment]
Hey @Richie-yan, I think a NCCL Allgather implementation would be a great addition.  Looking forward to the PR!

**Comment by Richie-yan** [comment]
@tgaddair Ok, I will provide the PR in the near future.
