### ISSUE TITLE
perf feature request: add a new env var to control 'allgather' vs 'allreduce'

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#433]
I found a performance problem for horovod related to allreduce implementation.

In horovod tensorflow implementation (tensorflow/__init__.py), the 'def allreduce()' function works like
 1) if tensor is tf.IndexedSlices, use allgather, which will call MPI_Allgather.
 2) else, use **_allreduce**, which can be mpi allreduce, nccl all reduce, etc.

After I found my code didn't performa well, I compared the performance between the above design and a new version where horovod will always use nccl allreduce (i.e. comment out allgather logic).

In my test, I am using NCCL2 over RDMA RoCE. I am running a tf machine translation model wmt32. I found my version is much faster (overall e2e >30%) than the allgather one.

**Feature request:** add a new env var in horovod so that either current implementation will be used, or **_allreduce** is always used.

**Comment by tgaddair** [comment]
Hi @LiweiPeng, thanks for the suggestion.  One question though: wouldn't this potentially be dangerous in cases where the indices from one rank differ from the indices from another rank for the same IndexedSlices tensor?  

In an allreduce implementation, we pack the elements of the tensor into a buffer and then reduce them, but it's possible that the first element of the buffer from rank 0 corresponds to index 10, while the first element of the buffer from rank 1 corresponds to index 20, for example.

So I believe that in order to make this work reliably, you would need to either (1) only apply it if you're sure that all ranks have the same indices in the IndexedSlices tensor, or (2) convert the sparse tensor to a dense tensor before allreduce.

In your experiments, did either of those things apply?

**Comment by LiweiPeng** [comment]
Thanks for the updates. I am not aware of this level of details for IndexedSlices tensor.  I'll see whether I can convert the sparse tensor to a dense tensor.

My original concern is that MPI allgather is slower than nccl APIs. So if the issue mentioned in https://github.com/uber/horovod/issues/430 is resolved, it may resolve my performance concern.

**Comment by alsrgv** [comment]
I concur with @tgaddair that this will unfortunately not work.  Replacing feature tags with a question.

**Comment by LiweiPeng** [comment]
I am not a tensorflow expert. Because of performance difference, I'd like to try what @tgaddair suggested. Questions:
1) how to I know whether all ranks have the same indices in the IndexedSlices tensor or not? I am using tensorflow to run a transformer model for machine translation problem.
2) how to convert sparse tensor to dense tensor? what's the cost for this extra step?

Thanks.

**Comment by alsrgv** [comment]
@LiweiPeng, most likely they will not have the same indices.  If they have the same indices it means they processed exactly the same sentence, which won't be true.

**Comment by tgaddair** [comment]
@LiweiPeng, [tf.sparse_to_dense](https://www.tensorflow.org/api_docs/python/tf/sparse_to_dense) is how you would do it in TensorFlow.  But that may be more costly than just doing the allgather with sparse tensors (still, may be worth experimenting with for your particular use case).

**Comment by anpark** [comment]
sparse to dense is a bad idea, not try it.
