### ISSUE TITLE
speed measured by global_step in the tensorflow_mnist.py example

### ISSUE THREAD

**Issue by pengsun** [uber/horovod#461]
Hi 
I noticed the discussion here:
https://github.com/uber/horovod/issues/71

in that case, can we simply say the 4-GPU processes `4.58787*4` steps/sec as the printed `global_step/sec: 4.5878`, while the 1-GPU processes `5.10516` steps/sec. So the speedup is `4.58787*4 / 5.10516` when taking the same batch_size? Is it a correct understanding of the "synchronous steps among all workers."  ?

**Comment by tgaddair** [comment]
Hey @pengsun, that's mostly correct.  The speedup you derived is right, but it's not quite right to say that in the 4-GPU case we're processing `4.58787*4` steps / sec.  We're still processing `4.58787` steps per second, but it just so happens that the **batch size** is larger (because the effective batch size is multiplied by 4).  So we're processing more images per step.  Does that make sense?

**Comment by pengsun** [comment]
Hi @tgaddair, Yes that makes sense, you strictly distinguish "step" and "batch size". As you said "The speedup you derived is right" and "he effective batch size is multiplied by 4", I guess we are talking about the same thing. Thanks for the explanation :)
