### ISSUE TITLE
how to run horovod with multi CPU

### ISSUE THREAD

**Issue by li7hui** [uber/horovod#614]
Hello,

I was trying to run the horovod with multi-CPU by the following command:

 mpirun --allow-run-as-root --host rdma21,rdma22,rdma23,rdma24 -np 4 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet101 -batch_size 64 --variable_update horovod --data_format=NHWC --device=cpu

However, the tf_cnn_benchmarks.py program got executed on each host for 24 hours, and never got finished. Could you please tell me how to run the tf_cnn_benchmarks.py with multi-CPU? I means the program can be get finished within a reasonable period of time.

**Comment by tgaddair** [comment]
In general, CPU training is going to be very, very slow compared to GPU training.  This isn't anything specific to Horovod, but just due to the cost of running the forward and backwards passes without GPUs.

Depending on what you're trying to measure, there are a number of knobs you can tune with `tf_cnn_benchmarks.py` to speed up performance:

- Try a less complex model.  Resnet50 should train a lot faster than Resnet101.
- Reduce the batch size.  You could try using a batch size of 8 instead of 64.
- Reduce the number of batches.  By default it trains for 100 batches, but 10 or 20 may be sufficient for your use case (`--num_batches`).

Let me know if you have further questions.

**Comment by tgaddair** [comment]
Glad you got it working!  Closing this for now.
