### ISSUE TITLE
running hvd-tensorflow in docker pulled from official docker hub, got " Read -1, expected 131072, errno = 1"

### ISSUE THREAD

**Issue by yyht** [uber/horovod#653]
![image](https://user-images.githubusercontent.com/14133687/48990494-a9f3fe00-f169-11e8-8baa-5d24b978f77a.png)
what does it mean?  did i do something wrong? 
![image](https://user-images.githubusercontent.com/14133687/48990600-06571d80-f16a-11e8-954d-0720b0a9663e.png)
but the process was still running

**Comment by byan23** [comment]
try adding "--privileged" to your docker command

**Comment by tgaddair** [comment]
Hey @yyht, did the suggestion given by @byan23 solve your issue?

**Comment by yyht** [comment]
Yes, thanks @tgaddair @byan23. Horovod is an excellent work, and helps me a lot for large-scale training

**Comment by tgaddair** [comment]
Thanks @yyht, glad it's working out for you!

**Comment by MichaelX99** [comment]
I am trying to run horovod inside a docker container on AWS Sagemaker which requires that the container to be run without privilege.  This is effectively a warning since training does work however it clutters up the log files.  Is there perhaps a catch that I can implement to not have the warnings written out to STDOUT?

**Comment by karakusc** [comment]
@alsrgv @MichaelX99 SageMaker does not allow running privileged containers, but you can set up a filter in CloudWatch to suppress these warnings.
