### ISSUE TITLE
undefined symbol: opal_cuda_check_bufs

### ISSUE THREAD

**Issue by hyciswu** [uber/horovod#69]
After i installed horovod and run the tensorflow_mnist.py, i get the following error.

python: symbol lookup error: /usr/local/lib/openmpi/mca_coll_cuda.so: undefined symbol: opal_cuda_check_bufs

**Comment by alsrgv** [comment]
@hyciswu,

This error sounds like an Open MPI installation problem. Which of the paths [here](https://github.com/uber/horovod/blob/master/docs/gpus.md) did you follow?

**Comment by hyciswu** [comment]
I followed `Horovod on GPU` path and installed mpi with
```bash
sudo ./configure  --prefix=/usr/local
sudo make install all
```

**Comment by alsrgv** [comment]
Can you try to run `sudo ldconfig` afterwards?

**Comment by hyciswu** [comment]
@alsrgv yap, tried that as well, and the same error occurs. also did
`export PATH=$PATH:/path/to/mpi/bin` and
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/mpi/lib`

**Comment by alsrgv** [comment]
@hyciswu, I think the problem is that you used to have a different version of Open MPI installed before (e.g. compiled with CUDA), and now your freshly installed Open MPI without CUDA is trying to pick up components of an old Open MPI installation by mistake.

You can try to perform a surgery to remove old Open MPI installation:
```
$ sudo rm -rf /usr/local/lib/openmpi /usr/local/lib/libmca* /usr/local/lib/libmpi* /usr/local/lib/libompitrace* /usr/local/lib/libopen* /usr/local/lib/liboshmem* /usr/local/lib/mpi_*
$ cd /where/your/mpi/sources/are
$ sudo make all install
```

**Comment by hyciswu** [comment]
It works now, thanks.
