### ISSUE TITLE
Converting horovod implementation of pytorch imagenet to without horovod

### ISSUE THREAD

**Issue by lakshmiumenon** [uber/horovod#788]
Hi,

I was trying to convert the pytorch_imagenet_resnet50.py in the examples folder to the code without using horovod to see the performance variation of both.

Could you please let me know what is the significance of t.update(1) in train function and how can I implement the same in a code which doesn't use horovod.

Thank You.

**Comment by tgaddair** [comment]
Hey @lakshmiumenon, [tqdm](https://github.com/tqdm/tqdm) is just a progress bar to visually track the progress of the training.  It's nothing specific to Horovod.  

There shouldn't be any noticeable difference between running the `pytorch_imagenet_resnet50.py` example with and without Horovod, because in the single process case (when you just run `python pytorch_imagenet_resnet50.py`), Horovod will not do anything special.

But, if you want to run it without any Horovod stuff, you can just remove the import statement `import horovod.torch as hvd` and then delete all lines that say `hvd.` something.  Replace `hvd.size()` with `1` and `hvd.rank()` with `0`, and you should be good to go.

Let me know if you have any other questions.

**Comment by lakshmiumenon** [comment]
> Hey @lakshmiumenon, [tqdm](https://github.com/tqdm/tqdm) is just a progress bar to visually track the progress of the training. It's nothing specific to Horovod.
> 
> There shouldn't be any noticeable difference between running the `pytorch_imagenet_resnet50.py` example with and without Horovod, because in the single process case (when you just run `python pytorch_imagenet_resnet50.py`), Horovod will not do anything special.
> 
> But, if you want to run it without any Horovod stuff, you can just remove the import statement `import horovod.torch as hvd` and then delete all lines that say `hvd.` something. Replace `hvd.size()` with `1` and `hvd.rank()` with `0`, and you should be good to go.
> 
> Let me know if you have any other questions.

Thank you so much..It worked..
