### ISSUE TITLE
Horovod pypi release doesn't have horovod.spark package

### ISSUE THREAD

**Issue by AnkBurov** [uber/horovod#818]
Hi. I'm following https://github.com/uber/horovod/blob/master/docs/spark.md guide and having the following error:
```
line 299, in <module>
    import horovod.spark
ImportError: No module named spark
```
IDE says there is no such package indeed:
![screenshot from 2019-02-08 19-23-25](https://user-images.githubusercontent.com/5352029/52490968-0dbd8d00-2bd7-11e9-88c1-a0d832b0bb71.png)
Horovod package version is 0.15.2

horovod-0.15.2.tar.gz in the Pypi repository also has no horovod.spark package inside: https://pypi.org/project/horovod/#files

Am I missing something?

**Comment by AnkBurov** [comment]
Renamed the issue, sorry I've been thinking about other things and accidentally wrote it down instead of horovod.spark

**Comment by tgaddair** [comment]
Hey @AnkBurov, PySpark integration has been landed to master, which is why it shows up in README.md docs on GitHub, but hasn't yet been released.  We plan on releasing it in `v0.15.3` which will be coming very shortly.  In the meantime, you can try installing from source if you'd like to start using `horovod.spark` now.

**Comment by AnkBurov** [comment]
Oh, it makes sense now. Thank you. I will wait the next release then. Hopefully it will be released soon. 
Thank you.

**Comment by alsrgv** [comment]
@AnkBurov, you can always install using `[flags] pip install git+https://github.com/uber/horovod` and get the latest master.
